language: java
sudo: true
dist: trusty
jdk: oraclejdk8

services:
  - mysql

coverage:
  range: 50..80
  round: down
  precision: 2

addons:
  apt:
    packages:
      - oracle-java8-installer
env:
  global:
    - CODECOV_TOKEN=6d0d7ff5-31c7-4798-a8b2-655e6a274a64
    - CC_TEST_REPORTER_ID=62c6b2ad694f8b15d00d369627284cc7c669437a5cdadc7ff98bce8070541b7d

before_install:
  - chmod +x mvnw
  - mysql -u root --password="" < db-scripts/setup.sql
  - mysql -u root --password="" < db-scripts/create.sql
  - mysql -u root --password="" < db-scripts/fill.sql
  - pip install --user codecov

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT