language: java
sudo: true
dist: trusty
jdk: oraclejdk8
services:
  - mysql
addons:
  apt:
    packages:
      - oracle-java8-installer
env:
  global:
    - CODECOV_TOKEN=6d0d7ff5-31c7-4798-a8b2-655e6a274a64

before_install:
  - chmod +x mvnw
  - mysql -u root --password="" < db-scripts/setup.sql
  - mysql -u root --password="" < db-scripts/create.sql
  - mysql -u root --password="" < db-scripts/fill.sql
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)